blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/shavonn/laravel-werkos/discussions/new?category=q-a
    about: Ask the community for help
  - name: Report a security issue
    url: https://github.com/shavonn/laravel-werkos/security/policy
    about: Learn how to notify us for sensitive bugs
